export const GrupoRespuestas = [
  [
    { text: "Hombre", id: 1 },
    { text: "Mujer", id: 2 },
  ],
  [
    { text: "Si", id: 1 },
    { text: "No", id: 2 },
  ],
  [
    { text: "Ninguno", id: 1 },
    { text: "Primaria", id: 2 },
    { text: "Secundaria", id: 3 },
    { text: "Técnica", id: 4 },
    { text: "Tecnológica", id: 5 },
    { text: "Universitario", id: 6 },
    { text: "Posgrado", id: 7 },
  ],
  [
    { text: "Mensaje de texto", id: 1 },
    { text: "Telegram", id: 2 },
    { text: "WhatsApp", id: 3 },
    { text: "Messenger", id: 4 },
    { text: "Instagram", id: 5 },
    { text: "Ninguno", id: 6 },
  ],
  [
    { text: "Facebook", id: 1 },
    { text: "YouTube", id: 2 },
    { text: "Twitter", id: 3 },
    { text: "Tik Tok", id: 4 },
    { text: "Instagram", id: 5 },
    { text: "Siembra", id: 6 },
    { text: "Agro net", id: 7 },
    { text: "Sofia Plus", id: 8 },
    { text: "Ninguna", id: 9 },
    //{ text: "Otra:", id: 10 },
  ],
  [
    { text: "Grupo A: Pobreza extrema A1 a A5", id: 1 },
    { text: "Grupo B: Pobreza moderada B1 a B7", id: 2 },
    { text: "Grupo C: Vulnerable C1 a C18", id: 3 },
    { text: "Grupo D: No pobre, no vulnerable D1 a D21", id: 4 },
  ],
  [
    { text: "Indígena", id: 1 },
    { text: "Gitano(a) Rom", id: 2 },
    { text: "Mulato", id: 3 },
    {
      text: "NARP-Negro(a), afrodescendiente, afrocolombiano(a), raizal, palenquero(a)",
      id: 4,
    },
    { text: "Ninguna de las anteriores", id: 5 },
  ],

  [
    { text: "Vivienda Familiar", id: 1 },
    { text: "Colegios-Escuelas, Biblioteca", id: 2 },
    { text: "Zonas WiFi", id: 3 },
    { text: "Establecimientos de servicios de internet", id: 4 },
    { text: "Servicio particular de internet", id: 5 },
    { text: "Red directa - Plan de datos - Celular", id: 6 },
    { text: "Vive digital", id: 7 },
    { text: "No accede", id: 8 },
  ],

  [
    { text: "Cooperativas", id: 1 },
    { text: "Gremios", id: 2 },
    { text: "Asociación de productores", id: 3 },
    { text: "Centro de Investigación", id: 4 },
    { text: "Consejo Comunitario", id: 5 },
    { text: "JAC", id: 6 },
    { text: "JAL", id: 7 },
    { text: "Asociación y organización étnica", id: 8 },
    { text: "Organizaciones comunitarias de mujeres", id: 9 },
    { text: "Organizaciones comunitarias de ancianos o de jóvenes", id: 10 },
    { text: "No pertenece a ninguna asociación", id: 11 },
    { text: "No sabe / no responde", id: 12 },
    //{ text: "Otro:", id: 13 },
  ],
  [
    { text: "Bancos", id: 1 },
    { text: "Gremial", id: 2 },
    { text: "Cooperativa", id: 3 },
    { text: "Fondos rotatorios de la asociación", id: 4 },
    { text: "Programa de Gobierno", id: 5 },
    { text: "Familiares o amigos", id: 6 },
    { text: "Gota o gota/Pago diario", id: 7 },
    { text: "Ninguno", id: 8 },
  ],

  [
    { text: "LEC-A toda máquina e infraestructura", id: 1 },
    { text: "LEC-Compra de tierras de uso agropecuario", id: 2 },
    { text: "LEC-Inclusión financiera", id: 3 },
    { text: "LEC-Comunicades Negras, Afrodescendientes, Raizales y Palenqueras", id: 4 },
    { text: "LEC-Mujer rural y joven rural", id: 5 },
    { text: "LEC-Sustitución", id: 6 },
    { text: "LEC-Sectores estratégicos", id: 7 },
    { text: "LEC-Reactivación productivaAfectaciones climáticas", id: 8 },
    { text: "LEC-Agricultura por contrato", id: 9 },
    { text: "LEC-Sostenibilidad agropecuaria y Negocios Verdes", id: 10 },
    { text: "Población en situación especial (Victimas, reinsertados)", id: 11 },
    { text: "Ninguno", id: 12 },
    //{ text: "Otro:", id: 13 },
  ],

  [
    { text: "Propio sin título", id: 1 },
    { text: "Propio con título", id: 2 },
    { text: "En arriendo o subarriendo", id: 3 },
    { text: "Aparcería", id: 4 },
    { text: "En usufructo", id: 5 },
    { text: "En sucesión con título", id: 6 },
    { text: "En sucesión sin título", id: 7 },
    { text: "Propiedad colectiva", id: 8 },
  ],

  [
    { text: "Hectáreas", id: 1 },
    { text: "Metros cuadrados", id: 2 },
    { text: "Cuadras", id: 3 },
    { text: "Fanegadas", id: 4 },
  ],

  [
    { text: "Interconexión eléctrica", id: 1 },
    { text: "Energía fotovoltaica o eólica", id: 2 },
    { text: "Gas domiciliario", id: 3 },
    { text: "Biogás", id: 4 },
    { text: "Sistema de riego", id: 5 },
    { text: "Unidad sanitaria", id: 6 },
    { text: "Pozo séptico", id: 7 },
    { text: "Señal de telefonía móvil", id: 8 },
    { text: "Acueducto", id: 9 },
    { text: "Internet", id: 10 },
  ],

  [
    { text: "Vía sin pavimentar", id: 1 },
    { text: "Sendero", id: 2 },
    { text: "Carretera", id: 3 },
    { text: "Fluvial", id: 4 },
  ],

  [
    { text: "Malo", id: 1 },
    { text: "Aceptable", id: 2 },
    { text: "Bueno", id: 3 },
  ],

  [
    { text: "Automóvil", id: 1 },
    { text: "Moto", id: 2 },
    { text: "Bicicleta", id: 3 },
    { text: "Transporte animal", id: 4 },
    { text: "Transporte público", id: 5 },
    { text: "Transporte aéreo", id: 6 },
    { text: "Transporte fluvial", id: 7 },
    { text: "Ninguno", id: 8 },
  ],

  [
    { text: "Hasta 30 minutos", id: 1 },
    { text: "Entre 31 minutos y 1 hora con 30 minutos", id: 2 },
    { text: "Más de 2 horas", id: 3 },
  ],

  [
    { text: "Río", id: 1 },
    { text: "Lago o laguna", id: 2 },
    { text: "Ciénaga o humedal", id: 3 },
    { text: "Embalse o represa", id: 4 },
    { text: "Pozos, aljibes, reservorios, estanques o jaguey", id: 5 },
    { text: "Fuente natural con sistema de captación", id: 6 },
    { text: "Acueducto", id: 7 },
    { text: "Carro tanque", id: 8 },
    { text: "Distrito de riego", id: 9 },
    { text: "Agua de lluvia", id: 10 },
    { text: "No tiene acceso al agua", id: 11 },
  ],

  [
    { text: "Permanente", id: 1 },
    { text: "Temporal (meses)", id: 2 },
    { text: "Temporal (días)", id: 3 },
  ],

  [
    { text: "Kilos", id: 1 },
    { text: "Toneladas", id: 2 },
    { text: "Arrobas", id: 3 },
    { text: "Bultos", id: 4 },
    { text: "Atados", id: 5 },
    { text: "Litros", id: 6 },
    { text: "Cargas", id: 7 },
    { text: "Galones", id: 8 },
    { text: "Cubetas", id: 9 },
  ],

  [
    { text: "Bovinos - Lechería Especializada", id: 1 },
    { text: "Derivados lácteos ", id: 2 },
    { text: "Bovinos - Ceba ", id: 3 },
    { text: "Bovinos - Derivados cárnicos ", id: 4 },
    { text: "Bovinos - Carne y leche (Doble propósito) ", id: 5 },
    { text: "Bovinos - Cría ", id: 6 },
    { text: "Búfalos - Carne ", id: 7 },
    { text: "Búfalos - Leche ", id: 8 },
    { text: "Avícola - Gallina Ponedora ", id: 9 },
    { text: "Avícola - pollos de engorde ", id: 10 },
    { text: "Avícola - Subproductos (vísceras, pescuezos, patas)", id: 11 },
    { text: "Avícola - para producción ", id: 12 },
    { text: "Avícola - Huevo fértil (incubadores)", id: 13 },
    { text: "Avícola - levante pollas ponedoras (16 semanas) ", id: 14 },
    { text: "Avícola - codornices", id: 15 },
    { text: "Avícola - pavos", id: 16 },
    { text: "Avícola - avestruces", id: 17 },
    { text: "Porcicola - Ceba ", id: 18 },
    { text: "Porcicola - semen", id: 19 },
    { text: "Porcicola - cría ", id: 20 },
    { text: "Apicultura - miel", id: 21 },
    { text: "Apicultura - polen", id: 22 },
    { text: "Apicultura - propóleo", id: 23 },
    { text: "Apicultura - cera", id: 24 },
    { text: "Apicultura - jalea real", id: 25 },
    { text: "Apicultura - api toxina", id: 26 },
    { text: "Apicultura - núcleos de abejas", id: 27 },
    { text: "Apicultura - me liponas", id: 28 },
    { text: "Conejos - carne", id: 29 },
    { text: "Cuy - carne", id: 30 },
    { text: "Ovina - Carne", id: 31 },
    { text: "Ovina - lana", id: 32 },
    { text: "Caprina - leche", id: 33 },
    { text: "Caprina - carne", id: 34 },
    { text: "Equina, Asnal y mular - carne", id: 35 },
    { text: "Equina, Asnal y mular - trabajo", id: 36 },
    { text: "Equino, asnal y mular - semen", id: 37 },
    { text: "Zoocria - babillas", id: 38 },
    { text: "Zoocria - chigüiros", id: 39 },
  ],
  [
    { text: "Acelga", id: 1 },
    { text: "Achiote", id: 2 },
    { text: "Agraz", id: 3 },
    { text: "Aguacate", id: 4 },
    { text: "Ahuyama - Zapallo", id: 5 },
    { text: "Ají",id: 6},
    { text: "Ajonjolí", id: 7 },
    { text: "Algodón confecciones y textiles", id: 8 },
    { text: "Anón", id: 9 },
    { text: "Apio", id: 10 },
    { text: "Arracacha", id: 11},
    { text: "Arroz", id: 12 },
    { text: "Azúcar", id: 13 },
    { text: "Babaco", id: 14 },
    { text: "Badea", id: 15},
    { text: "Banano", id: 16},
    { text: "Batata", id: 17},
    { text: "Berenjena", id: 18},
    { text: "Berro", id: 19},
    { text: "Cacao", id: 20},
    { text: "Café", id: 21},
    { text: "Cebollín", id: 22},
    { text: "Chontaduro", id: 23},
    { text: "Cimarrón", id: 24},
    { text: "Coco", id: 25},
    { text: "Flores y forrajes", id: 26},
    { text: "Acuícola - pesca artesanal", id: 27},
    { text: "Acuícola - Cachama de cultivo fresca", id: 28},
    { text: "Acuícola - Camarón de cultivo", id: 29},
    { text: "Acuícola - Filetes de tilapia frescos o refrigerados" , id: 30},
    { text: "Acuícola Tilapia roja entera fresca", id:31},
    { text: "Acuícola Roja entera congelada", id: 32},
    { text: "Acuícola plateada entera fresca", id: 33},
    { text: "Acuícola - Trucha entera fresca", id: 34},
    { text: "Bocachico - cultivo fresco", id: 35},
    { text: "Bagre - cultivo fresco", id: 36},
    { text: "Yamú - cultivo fresco", id: 37},
    { text: "Alcachofa", id: 38},
  ],
  [
    { text: "Diaria", id: 1 },
    { text: "Semanal", id: 2 },
    { text: "Mensual", id: 3 },
    { text: "Trimestral", id: 4 },
    { text: "1 vez al año", id: 5 },
    { text: "2 veces al año", id: 6 },
    { text: "3 veces al año", id: 7 },
  ],
  [
    { text: "Plazas de mercado", id: 1 },
    { text: "Intermediarios", id: 2 },
    { text: "Empresas", id: 3 },
    { text: "Mercados Campesinos", id: 4 },
    { text: "Compras públicas", id: 5 },
    { text: "Tiendas",id: 6},
    { text: "Cooperativas", id: 7 },
    { text: "Gremios", id: 8 },
    { text: "Exportadores", id: 9},
    { text: "Mayoristas", id: 10 },
    { text: "Almacenes de cadena grandes superficies", id: 11 },
    { text: "NInguna", id: 12 },    


  ]

];



